### ISSUE TITLE
POST parameters not working

### ISSUE THREAD

**Issue by ClayBirkett** [plantbreeding/IPK-BrAPI-Validator#17]
I don't think the POST parameters are working for calls such as allelematrix-search. Should you be using the param("param1", "value1") statement in the code instead of defining the parameter in the url?

Clay Birkett

**Comment by BrapiCoordinatorSelby** [comment]
@ClayBirkett are you looking at the [hosted version](http://webapps.ipk-gatersleben.de/brapivalidator/) or are you running a local copy of the validator?

I changed some code about a month ago which fixed the POST calls on my local, but I don't think that code has been deployed to the hosted version yet. @martinbaste is that right?

Clay if you are seeing a problem on your local and you have the most updated version, then I probably screwed something up with my edits.

**Comment by ClayBirkett** [comment]
I am using the hosted version. Can you ask the people who are hosting to update?

**Comment by martinbaste** [comment]
I'll update it first thing on Monday! Thanks for the tip, I´ll close this when fixed

**Comment by martinbaste** [comment]
Hi,
@ClayBirkett is right, the parameters are set in the URL for both GET and POST. POST should have them in the body. @BrapiCoordinatorSelby's fix adds an empty object to the body, but we need to add the parameters for the POST requests there. 

I'll update this when it is fixed

**Comment by martinbaste** [comment]
I added a new object to the test config files: parameter. Now for those 3-4 tests that have parameters, they will be added to the URL if they are GET and to the body if they are POST. 

I couldn't test it with a real server because I think none of the ones publicly available on the JSON list have these calls enabled. @ClayBirkett, let me know if it works.

@BrapiCoordinatorSelby, I had to remove the .body({}) line, because I suspect that it will interfere with Rest Assured's mechanism of adding parameters to the body (I haven't tested though). Is it ok, or should POST request always contain a body (even if empty)?

**Comment by BrapiCoordinatorSelby** [comment]
proposed fix at #18 

test-server.brapi.org has all the calls enabled ... I need to remember to add it to that public implementation list.

test-server uses Java Spring as a back end controller and doesn't accept an empty body on a post request. This makes sense because an empty string is not valid JSON. So every POST request which has a content type of 'application/json' there must be some valid json in the body.

Rest Assured `RequestSpecification.param()` method only applies to URL parmeters, it doesn't do anything with the request body. In #18 I broke out the logic to explicitly add a body with params if it is a POST request. I have tested this fix with test-server and it appears to be working.

**Comment by martinbaste** [comment]
Got it. I thought that Rest Assured .param() adds the params as JSON, but it actually adds them as form parameters. 

It makes sense that the server expects a body when you specify a content type of 'application/json'. I'll update the live version.
