### ISSUE TITLE
Test your own: 503 Service Unavailable

### ISSUE THREAD

**Issue by nahuel-soldevilla** [plantbreeding/IPK-BrAPI-Validator#45]
I'm trying to run the validator (http://webapps.ipk-gatersleben.de/brapivalidator/) against the BMS server: http://www.bms-uat-test.net:48080/bmsapi/brapi/v1, but it fails on the calls call with `Response Status code: 503` (Service Unavailable).
**It works when I run the validator locally** using maven, with advance configuration, against the same server, so I'm not sure if it's something wrong the BMS server or the validator site.

cc @mcrimi

### Details
- url: http://www.bms-uat-test.net:48080/bmsapi/brapi/v1
- BrAPI version: v1.3
- Token: (get token using http://www.bms-uat-test.net:48080/bmsapi/brapi/v1/token, username: _test1_, password: _test1_)

**Comment by langeipk** [comment]
Validating endpoints that are not running at standard HTTP(s) ports can only be tested locally. This is because public BrAPI endpoints need to generally publicly accessible. Clients firewall and proxy configuration usually blocking non-standard port, like the one you used. Once your endpoint is moved to port 80,the validator may used for scheduled automated test

**Comment by nahuel-soldevilla** [comment]
thanks @langeipk
